version: '3'
services:
  web:
    build: ./docker/httpd
    ports:
      - "80:80"
    volumes:
      - ./:/usr/local/apache2/htdocs/
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '443:443'
    restart: always
    environment:
      STAGE: local
      DOMAINS: 'localhost -> http://host.docker.internal:80'
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'